# Generated by Django 4.0.5 on 2022-07-05 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField(auto_now_add=True)),
                ('paid', models.BooleanField(default=False)),
                ('course_registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.courseregistration')),
            ],
            options={
                'verbose_name_plural': 'Course Orders',
            },
        ),
    ]
