# Generated by Django 4.0.5 on 2022-07-05 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_courseorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseregistration',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='CourseOrder',
        ),
    ]
