# Generated by Django 4.0.5 on 2022-07-05 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_customuser_is_verified_customuser_otp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Visitors',
        ),
    ]
